import Head from "next/head";

export default function Home() {
  return (
    <div className="h-screen bg-slate-900 text-slate-300 flex justify-center items-center">
      <Head>
        <title>Next.js + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello World
    </div>
  );
}
