import Head from "next/head";
import { Menu } from "@/features/menu/components/Menu";

interface HomePageProps {
  menuItems: MenuItem[];
}
export const HomePage = ({ menuItems }: HomePageProps) => {
  return (
    <div className="h-screen bg-slate-900 text-slate-300 flex justify-center items-center">
      <Head>
        <title>Next.js + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu items={menuItems} />
      <div className="a">a Content</div>
    </div>
  );
};
