import Head from "next/head";
import { Menu } from "@/features/menu/components/Menu";
import { Logo } from "@/features/core/components/Logo";
import { HomeScreen } from "@/features/home/components/HomeScreen";

interface HomePageProps {
  menuItems: MenuItem[];
}
export const HomePage = ({ menuItems }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Next.js + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen menuItems={menuItems} />
      <HomeScreen menuItems={menuItems} />
      <HomeScreen menuItems={menuItems} />
      <HomeScreen menuItems={menuItems} />
    </>
  );
};
